/*
* generated by Xtext
*/
package jp.ac.nii.prg.bxauthz;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BxAuthZStandaloneSetup extends BxAuthZStandaloneSetupGenerated{

	public static void doSetup() {
		new BxAuthZStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

