/*
 * generated by Xtext
 */
package jp.ac.nii.prg.bxauthz;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BxAuthZRuntimeModule extends jp.ac.nii.prg.bxauthz.AbstractBxAuthZRuntimeModule {

}
