/*
 * generated by Xtext
 */
package jp.ac.nii.prg.bxauthz.validation

import jp.ac.nii.prg.bxauthz.bxAuthZ.Policy
import org.eclipse.xtext.validation.Check
import jp.ac.nii.prg.bxauthz.bxAuthZ.BxAuthZPackage

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class BxAuthZValidator extends AbstractBxAuthZValidator {
	public static var EMPTY_POLICY = "jp.ac.nii.prg.bxauthz.EmptyPolicy"
	
	@Check
	def checkEmptyPolicy(Policy policy) {
		if (policy.rules.isEmpty())
			warning('''Policy contains no rule''',
				BxAuthZPackage::eINSTANCE.policy_Name,
				EMPTY_POLICY
			)
	}

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
}
