/*
 * generated by Xtext
 */
package jp.ac.nii.prg.bxauthz.validation

import jp.ac.nii.prg.bxauthz.bxAuthZ.Policy
import org.eclipse.xtext.validation.Check
import jp.ac.nii.prg.bxauthz.bxAuthZ.BxAuthZPackage

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class BxAuthZValidator extends AbstractBxAuthZValidator {
	public static var EMPTY_POLICY = "jp.ac.nii.prg.bxauthz.EmptyPolicy"
	
	@Check
	def checkEmptyPolicy(Policy policy) {
		if (policy.rules.isEmpty())
			warning('''Policy contains no rule''',
				BxAuthZPackage::eINSTANCE.policy_Name,
				EMPTY_POLICY
			)
	}
}
